### ISSUE TITLE
Nil telescope mapping crashes

### ISSUE THREAD

**Issue by vitaliydolbilov** [gbprod/yanky.nvim#108]
Hi there, thanks for the great plugin!

A really minor issue - when using the telescope plugin, with default yanky settings (`require("yanky").setup({})`), I get the following error - `Error executing Lua callback: .../plugged/yanky.nvim/lua/yanky/telescope/yank_history.lua:51: attempt to index field 'mappings' (a nil value)` when calling `:Telescope yank_history`

Also crashes when setting 
```
require("yanky").setup({
	picker = {
		telescope = {
			mappings = nil,
		},
	},
})
```

This is fixed by copy pasting the default mapping config from the docs. 

I would expect it not to crash since the docs say set mappings to `nil` to use the default value

**Comment by gualcasas** [comment]
I'm encountering the same problem, and this solution is not fixing it for me.

**Comment by gbprod** [comment]
Hi!

Sorry for that, I'm pretty sure it comes from one of my latest commit : https://github.com/gbprod/yanky.nvim/commit/406d6199b231cfa4a5c51a122ff017fd93be24bb

I would like to revert this commit but I won't have a computer before the end of the week... If someone can PR me a revert, I'll merge it, if not, we'll have to wait until next week 😅

Otherwise, you can use the previous commit instead of main : https://github.com/gbprod/yanky.nvim/commit/c4c794afd762a00ca543972e5b9e34ce9aa14a87
