### ISSUE TITLE
Compatibility with ReplaceWithRegister

### ISSUE THREAD

**Issue by piersolenski** [gbprod/yanky.nvim#19]
Is there any way to make this compatible with https://github.com/vim-scripts/ReplaceWithRegister? At the moment it will warn that `Your last action was not put, ignoring cycle` when replacing the text rather than putting it. Thanks in advance, cool plugin!

**Comment by gbprod** [comment]
I'm not familiar with ReplaceWithRegister but I can try to do something, can you provide a minimal config ? I'll try something today

(PS: It seems that ReplaceWithRegister do something similar to another of my plugins, have a look to [substitute.nvim](https://github.com/gbprod/substitute.nvim/) ;) )

**Comment by piersolenski** [comment]
You don't need any configuration with that plugin, it just works ☺️ - will check out your plugin properly when I get a moment, looks cool!

**Comment by gbprod** [comment]
Hi, sorry, for the moment, I can't manage to make it works with https://github.com/vim-scripts/ReplaceWithRegister... I think it's because it use tpope/vim-repeat to manage repeatability. I'll make more tries later.

However, if you want to try [substitute.nvim](https://github.com/gbprod/substitute.nvim/), to have something similar to ReplaceWithRegister, just do :

```lua
use("gbprod/yanky.nvim")
use("gbprod/substitute.nvim")

require("substitute").setup({
  on_substitute = function(event)
    require("yanky").init_ring("p", event.register, event.count, event.vmode:match("[vV]"))
  end,
})

vim.keymap.set("n", "gr", "<cmd>lua require('substitute').operator()<cr>", { noremap = true })
vim.keymap.set("n", "grr", "<cmd>lua require('substitute').line()<cr>", { noremap = true })
vim.keymap.set("x", "gr", "<cmd>lua require('substitute').visual()<cr>", { noremap = true })
```
